import { contentCard, TermsType } from "@/types";

export const openingParagraphs: contentCard[] = [
  {
    id: 1,
    content: `This User Agreement for the service "HoxDEX" (hereinafter the "Agreement") is concluded between the owner of the software package "HoxDEX" (hereinafter "CRYPTO ARBY TRADE LIMITED") and a person who successfully registered on the service "HoxDEX" (hereinafter "Service") and started using the Service ( hereinafter referred to as "User").`,
  },
  {
    id: 2,
    content: `The User is obliged to study the text of this Agreement in detail. Acceptance of this Agreement by successfully registering on the Service and starting to use it means full and unconditional acceptance the Agreement terms and other information, links to which are provided in the Agreement. `,
  },
  {
    id: 3,
    content:
      "In case of disagreement with this terms, the User is obliged to immediately leave the Service.",
  },
  {
    id: 4,
    content:
      "The User is granted any proprietary intellectual rights in relation to the Service and its software under no circumstances.",
  },
];

export const agreement: TermsType[] = [
  {
    id: 1,
    title: "1. Definitions and term interpretations.",
    paragraphs: [
      "1.1 The terms given below are used in this document with the following meanings: ",
      "1.1.1 «User» - the person who has reached the age of majority, the visitor of the Service, who acquaints himself with the types of Services presented by CRYPTO ARBY TRADE LIMITED, uses the reference and information resources of the Service, is going to make the Order of Services, or already implements the Order in the real-time mode, or who is already using Services purchased from CRYPTO ARBY TRADE LIMITED. ",
      "1.1.2 «Service» is a software complex «HoxDEX», located at https://hoxdex.com and owned by CRYPTO ARBY TRADE LIMITED, containing all technical and functional features for use by the User following the terms and conditions described in the Agreement. The service is a simulator of an online crypto exchange (analogous to a crypto exchange), where the User has the opportunity to learn trading making crypto-coins exchange transactions. ",
      `1.1.3 «Services» - services provided by CRYPTO ARBY TRADE LIMITED to Users, including the provision for using of Service functionality for a certain period under the Subscriptions selected by the User, Agreement terms. `,
      "1.1.4 «Subscription» - the totality of functions provided to the User during the paid period of the Service using. Details of the current subscriptions are listed on the Service page https://hoxdex.com",
      "1.1.5 «Agreement» - a service agreement concluded between CRYPTO ARBY TRADE LIMITED and the User by registering the User on the Service and creating a PA.",
      "1.1.6 «Order» - an application of the User for the Services receipt, issued through the Service and representing the free and independent intention and will of the User to purchase the Service selected by the User from CRYPTO ARBY TRADE LIMITED under the Subscription.",
      "1.1.7 «Personal Account» ('PA') is a personalized Service section, closed for public access. Access to the personal account is carried out by entering authentication data on the Service login page: login and password.",
      "1.2 Terms that are not defined in Agreement clause 1.1 may be used in the Agreement. In these cases, the interpretation of the terms is made under the text and meaning of the Agreement. In the absence of an unambiguous term interpretation in the text of the Agreement, you should be guided, firstly, by the interpretation of the terms used on the Service, including in the legal documentation posted on the Service; secondly, by international law and business customs in the relevant field of activity.",
    ],
  },
  {
    id: 2,
    title: "2. Subject of the Agreement",
    paragraphs: [
      "2.1 Under this Agreement, CRYPTO ARBY TRADE LIMITED, within the framework of the Subscription chosen by the User, grants the User the right to access and use the Service in the manner described in the Agreement. By accepting the terms of this Agreement and creating a Personal Account on the Service, the User agrees to follow and comply with all the rules and requirements for using the Service specified in the Agreement.",
      "2.2 Searching, ordering a service, using the Service, including viewing those posted in the sections of the Service, providing reference and information resources of the Service, also implies full consent of the User with this Agreement.",
      "2.3 CRYPTO ARBY TRADE LIMITED, after the registration procedure and creation of the PA, provides the User with the following Service functionality:",
      "2.3.1 Studying the operation principles of crypto-exchanges.",
      "2.3.2 Depositing crypto-coins (bitcoin, ethereum, or litecoin) to your private account (wallet) located on the Service, and withdrawing them from the Service at your discretion.",
      "2.3.3 Trading on a demo account.",
      "2.3.4 Tracking balance indicators, transactions history in the User's PA.",
      "2.3.5 Using a simulator of investment plans, where the User can invest his/her coins at a certain percentage and freeze them for the period specified in the plan.",
      "2.4 The user has the right to use the Service without restrictions on any territory, on the terms, and in the manner provided for in this Agreement.",
      "2.5 A full description of the Services, the method of ordering them, a list of valid Subscriptions, as well as other information, are described on the corresponding web page of the Service and/or in the User's private account.",
      "2.6 The use of the Service is carried out by the User independently under the instructions posted in the PA.",
      "2.7 CRYPTO ARBY TRADE LIMITED has the right to amend the Agreement without notifying the User. The user is personally responsible for checking the Agreement for changes in it. If the User disagrees with the relevant changes, the User is obliged to stop using the Service and refuse the Services provided by CRYPTO ARBY TRADE LIMITED. Otherwise, the continued use of the Service by the User means that the User agrees with the terms of the Agreement in the new edition.",
      "2.8 The Agreement does not require seals and/or signing by CRYPTO ARBY TRADE LIMITED and the User on paper to maintain full legal force.",
      "2.9 By registering on the Service and thereby creating a Personal Account, the User guarantees that he/she has the legal rights to enter into legal relations with CRYPTO ARBY TRADE LIMITED. In this case, the User agrees that:",
      "2.9.1 The User's data during registration and authorization to enter the Service are indicated by him/her voluntarily.",
      "2.9.2 Other data voluntarily specified by the User are transmitted to CRYPTO ARBY TRADE LIMITED in electronic form via Internet communication channels.",
      "2.9.3 The data is transferred by User to CRYPTO ARBY TRADE LIMITED for the implementation of the purposes specified in this Agreement.",
      "2.9.4 The consent given by the User to the processing of his/her data is indefinite and can be revoked by the User or his/her legal representative by submitting a written application to CRYPTO ARBY TRADE LIMITED.",
    ],
  },
  {
    id: 3,
    title: "3. Registration",
    paragraphs: [
      "3.1 The provision of the Services to the User is possible subject to the creation of an appropriate account by the User on the Service for the subsequent entry into the PA in order to gain access to the functionality of the Service.",
      "3.2 Viewing information posted on the Service in the public domain does not require registration and/or User authorization, however, when performing such actions, the User is in any case obliged to comply with the provisions of the Agreement.",
      "3.3 The registration account must contain the User's login, email address, password.",
      "3.4 Account registration is carried out by filling out the registration form. In the registration form, it is necessary to indicate only authentic data. Mandatory forms are indicated with a '*'.",
      "3.5 When registering, the User is assigned a login and password, and the User gains access to his/her PA.",
      "3.6 The user is solely responsible for his/her login and password safety. CRYPTO ARBY TRADE LIMITED is not responsible for the disclosure of the User's login and password to third parties and in the event of unauthorized access by third parties to the User's account.",
    ],
  },
  {
    id: 4,
    title: "4. The Procedure of Ordering and Service using",
    paragraphs: [
      "4.1 After completing the registration procedure, the User has the right to place an Order for the Service under the Subscription chosen by him/her, presented on the Service. Thus, the User, implementing the algorithm proposed by the Service, independently creates an Order through the appropriate web interface.",
      "4.2 Choosing a Subscription, placing an Order, and all subsequent User's actions described in this section are carried out independently, without the participation of CRYPTO ARBY TRADE LIMITED.",
      "4.3 The payment method and the performance actions of other related necessary in connection with the requirements of the corresponding selected payment system are the responsibility of the User.",
      "4.4 The User assumes full responsibility for providing incorrect data, which can make it impossible for CRYPTO ARBY TRADE LIMITED to properly execute this Agreement.",
      "4.5 The User has the right to deposit crypto-coins (bitcoin, ethereum, or litecoin) to his/her personal account (wallet) located on the Service and withdraw them from the Service at his/her own discretion.",
      "4.6 Trading is carried out on the User's demo account.",
      "4.7 The deposited crypto-coins can be used by the User to study the principles of the crypto-exchange (create orders for sale/purchase).",
      "4.8 The User can track balance indicators, the transactions history in the PA, as well as use an investment plans simulator, where he/she can invest his/her coins at a certain percentage and freeze them for the period specified in the plan.",
    ],
  },
  {
    id: 5,
    title: "5. Financial Terms",
    paragraphs: [
      "5.1 The cost of the Services is determined by CRYPTO ARBY TRADE LIMITED independently by introducing fees and their descriptions on the page https://hoxdex.com/fees.",
      "5.2 CRYPTO ARBY TRADE LIMITED has the right to unilaterally change the types and cost of Subscriptions without notifying the User about it at any time.",
      "5.3 Payment for fees is carried out in the ways presented on the Service.",
      "5.4 The User voluntarily and informed disposes of his/her funds for the personal use of the Service and pays for fees at own risk and peril. Unless the User proves otherwise, any actions performed by him/her using the Service are considered to have been committed by the relevant User.",
      "5.5 The Agreement concluded between the parties has the force of an act on the provision of Services. Acceptance and transfer of the Goods are made without signing the relevant acts between the Parties. If within 5 (five) working days from the end of the Subscription, CRYPTO ARBY TRADE LIMITED does not receive claims from the User related to the provision of the Services, their volume, and quality, the Parties will consider that the Services were provided to the User in full and properly. CRYPTO ARBY TRADE LIMITED doesn't accept subsequent claims from the User.",
      "5.6 Users with a balance of more than 500$ must activate the VIP status. In any other case, their balance will be frozen until the VIP account is activated.",
      "5.7 Deposit for purchasing VIP status and insurance payment should be done by one payment.",
      "5.8 To use the procedure for withdrawing funds from your account, the user needs to verify the wallet for withdrawal.",
    ],
  },
  {
    id: 6,
    title: "6. Rights and Obligations of the Parties",
    paragraphs: [
      "6.1 CRYPTO ARBY TRADE LIMITED undertakes:",
      "6.1.1 Accept the User's Order under the forms established on the Service.",
      "6.1.2 Provide accurate information about the Services.",
      "6.1.3 Provide the relevant Service based on the Order.",
      "6.1.4 Provide oral and written advice to the User on additional Users' questions.",
      "6.1.5 Ensure timely provision of Services.",
      "6.1.6 Use the information provided by the User only for the provision of the Services.",
      "6.1.7 Consider and verify motivated claims from the User.",
      "6.2 CRYPTO ARBY TRADE LIMITED is entitled to:",
      "6.2.1 Request any documents, personal data necessary to confirm the user's identity, as well as requests to clarify the legitimacy of funds origin that the User has deposited into his/her account.",
      "6.2.2 Freeze the User's funds withdrawal in case of illegal User's actions and the illegitimacy of funds deposited by User into his/her account located on the Service.",
      "6.2.3 Refuse to fulfill the Agreement unilaterally if the User infringes the conditions specified in the Agreement.",
      "6.2.4 Expand and reduce the Service's offers, regulate access to ordering Services, as well as suspend or terminate the implementation of any Services at its sole discretion.",
      "6.2.5 Change the Agreement terms unilaterally.",
      "6.2.6 Receive from the User any information necessary to fulfill their obligations under the Agreement.",
      "6.2.7 Suspend the operation of the Service at any time without prior notice to update the Service, carry out preventive maintenance, in the event of technical failures, by the action and/or inaction of third parties, and for other reasons beyond the control of CRYPTO ARBY TRADE LIMITED.",
      "6.2.8 For infringe of the terms of the Agreement, block the User's access to the Service without explaining the reasons.",
      "6.3 The User undertakes:",
      "6.3.1 To get acquainted with information about the Services, the terms of their purchase, Subscriptions, and other information before placing an Order.",
      "6.3.2 Provide only reliable data during registration.",
      "6.3.3 To act in good faith and not abuse your rights, in particular, not to purchase the Services to commit unfair actions that cause damage, loss, or cost to CRYPTO ARBY TRADE LIMITED.",
      "6.3.4 Do not attempt to gain unauthorized access to the Service, accounts registered with other people or other computers, Servers or networks connected to the Service in any other way than the user interface of the Service, including but not limited to bypassing or modifying, trying to bypass or change, or encourage or help any other person to circumvent or change the security software, technology, device or software that is part of the Service.",
      "6.3.5 Do not interfere with or attempt to interfere with the proper functioning of the Service or connect to the Service or use the Service in any way not expressly permitted by this Agreement.",
      "6.3.6 Do not use the information received from CRYPTO ARBY TRADE LIMITED in ways that could damage the interests of CRYPTO ARBY TRADE LIMITED.",
      "6.3.7 Do not copy, modify or distribute the rights to the content available in the Service, as well as the copyrights or trademarks of CRYPTO ARBY TRADE LIMITED, or use in any way, copy or distribute the content of the Service.",
      "6.3.8 Immediately notify CRYPTO ARBY TRADE LIMITED of any claims to the Service (if any).",
      "6.3.9 Do not publicly distribute information (correspondence in whole or in part) obtained as a result of communication with the technical support group of CRYPTO ARBY TRADE LIMITED.",
      "6.4 The User has the right to:",
      "6.4.1 Demand from CRYPTO ARBY TRADE LIMITED the proper and timely Services provision.",
      "6.4.2 Select Subscriptions.",
      "6.4.3 Contact CRYPTO ARBY TRADE LIMITED for all questions related to the provision of the Services.",
    ],
  },
  {
    id: 7,
    title: "7.Documentation disclaimer.",
    paragraphs: [
      "7.1 CRYPTO ARBY TRADE LIMITED does not force the User in any way, does not insist to do any actions through the Service.",
      "7.2 CRYPTO ARBY TRADE LIMITED does not provide the User with any financial, investment, or legal advice through the Service, providing its Services and managing the Service at its current stage of development. Although measures have been taken to ensure the accuracy of the information on the Service, CRYPTO ARBY TRADE LIMITED assumes no responsibility.",
      "7.3 The Service is not a virtual currency exchange house, it is a simulator (game resource), and therefore the Service and the results of the Services have nothing to do with real financial processes and cryptocurrency exchange platforms.",
      "7.4 CRYPTO ARBY TRADE LIMITED does not guarantee or make any representations regarding the Service security. The User acknowledges that any information sent to him/her can be intercepted. CRYPTO ARBY TRADE LIMITED does not warrant that the Service or the servers that make this Service available are free of viruses or any other harmful elements.",
      "7.5 CRYPTO ARBY TRADE LIMITED does not guarantee that the User will receive profit or loss similar to those shown on the Service. Actual percentage gains/losses may vary depending on many factors, including but not limited to: opening balances (deposits and withdrawals), market behavior, user account settings on the applicable cryptocurrency exchange. Because of this, the actual profit/loss incurred by the User may differ materially from the percentage gain/loss presented on the Service during the User's receipt of the Services.",
      "7.6 No part of the information provided and/or available on the Service is not intended to be provided and should not be construed as providing any investment, tax, or other financial advice of any kind. The User should not consider any such content and/or any such function as a substitute for professional financial advice. If the User decides to participate in any transactions on the exchanges based on the content and results obtained on the Service, then such a decision, operations, and their consequences are solely the User's responsibility.",
      "7.7 The User acknowledges and agrees, that:",
      "7.7.1. The Service using is carried out by the User at own risk and peril. CRYPTO ARBY TRADE LIMITED, as well as its employees and agents, are not investment or financial advisers who guarantee the receipt of income by the User through the use of the Service. If the User makes investment decisions relying on the information that is available on the Service, the User does so at his/her peril and risk, and CRYPTO ARBY TRADE LIMITED, its employees, and agents will not be liable for any losses that the User may get.",
      "7.7.2. The User should not make any investment decisions in real financial transactions on exchanges without conducting his/her own research. The user is exclusively and solely responsible for determining whether any investment, strategy, or any other product or service is appropriate for him/her based on the User's investment goals and personal and financial situation.",
      "7.7.3. The User is responsible for any damage caused to his/her device, data loss, or other harm that results from using the Service.",
      "7.7.4. No oral or written advice or information received by the User from CRYPTO ARBY TRADE LIMITED or the Service does not create any guarantees not expressly specified in the Agreement.",
      "7.7.5. The User pays for Subscriptions to obtain the result of the Services on a voluntary basis.",
      "7.7.6. The User is responsible for his/her actions performed on the Service or account on the Exchange.",
      "7.7.7. The content of the Service and the Services purchased by the User are provided on an 'as is' basis. At the same time, CRYPTO ARBY TRADE LIMITED is not responsible in any form for the discrepancy between the result of the Services and the goals, objectives, ideas, or desires of the User.",
      "7.7.8. Nothing in the Agreement can guarantee the complete satisfaction of User interests and needs related to the purchase of the Services.",
      "7.8. CRYPTO ARBY TRADE LIMITED is not responsible for:",
      "7.8.1. Risks, actions/inactions of the User in the cryptocurrency market.",
      "7.8.2. For losses and expenses incurred by the User, in particular, losses and expenses caused by the actions/inaction of third parties and/or incurred in connection with failures and interruptions in the operation of the Service and/or incurred in connection with the impact of computer viruses, 'Trojans', 'Worms', etc. and/or related to the blocking of the User using the Services result after ordering it, regardless of the reason for blocking.",
      "7.8.3. For any direct, indirect, consequential, punitive, special or incidental damages (including, without limitation, damages from business loss, contract, income, data, information or business interruption), according to any theory of liability, as a result, arising from or in connection with the use or inability to use the Service or the content, products, services, statements or behavior of any third party on the Service or through this Service.",
      "7.8.4. For the correct settings, practical application, and results of the trading bot used by the User through the Service;",
      "7.8.5. For the User's account on the Exchange.",
      "7.8.6. For non-receipt of the Services result by the User for reasons beyond the control of CRYPTO ARBY TRADE LIMITED (the User does not have the necessary software, the ability to access the Internet, the actions of providers, energy companies, the Exchange, the impact of any computer virus or other similar software code downloaded by the User to his/her device from the Service or in connection with any Service offered through the Service, etc.).",
      "7.8.7. For the practical applicability and value of information related to the Services.",
      "7.8.8. For failure to obtain the Services results below the User's expectations, since the success of the User's use of the knowledge, skills, and abilities reflected in the analytical information depends on many known and unknown CRYPTO ARBY TRADE LIMITED factors, which is accepted by both Parties.",
      "7.9. The Service may contain links to other sites that are not under the control of CRYPTO ARBY TRADE LIMITED. CRYPTO ARBY TRADE LIMITED is not responsible for the content of such sites.",
    ],
  },
  {
    id: 8,
    title: "8. Settlement of disputes.",
    paragraphs: [
      "8.1 All disputes, disagreements, and claims of the Parties must strive to resolve through negotiations. The Party that has claims and/or disagreements must send a message to the other Party indicating the claims and/or disagreements that have arisen.",
      "8.2 The message must be sent by the User in e-mail to the address contact{{ $_SERVER['HTTP_HOST'] }}. The message must contain the essence of the requirement, evidence supporting the requirement.",
      "8.3 Within 10 (ten) days from the date of the original message receipt, the Party that received it is obliged to send a response to this message.",
      "8.4 If the reply to the message is not received by the Party that sent the message within 10 (ten) days from the date of sending the corresponding message, or if the Parties do not come to an agreement on the claims and/or disagreements that have arisen, the dispute must be considered in court under the law.",
      "8.5 The applicable law under this Agreement is the substantive and procedural law of the United Kingdom of Great Britain.",
    ],
  },
  {
    id: 9,
    title: "9. Duration of Agreement.",
    paragraphs: [
      "9.1 The Agreement comes into force from the moment it is posted on the Internet on the Service, for the User - from the moment of his/her joining the terms (acceptance of the terms) of the Agreement.",
      "9.2 The Agreement has been posted for an indefinite period. The Agreement continues to operate for the User until the moment he/she stops using the Service. The User has the right to terminate access to the Service and its use at will at any time.",
      "9.3 Any changes to the Agreement made by CRYPTO ARBY TRADE LIMITED unilaterally come into force on the day following the day such changes are published on the Service.",
      "9.4 The User agrees and acknowledges that making changes to the Agreement entails the introduction of these changes into the Agreement concluded and in force between the User and CRYPTO ARBY TRADE LIMITED, and these changes come into force simultaneously with such changes to the Agreement.",
      "9.5 CRYPTO ARBY TRADE LIMITED may decide to terminate the Agreement unilaterally at any time with the immediate termination of access and the ability to use the Service by Users in the event of the Service closure, and in case of violation by the User of any Agreement provision.",
    ],
  },
  {
    id: 10,
    title: "10. Additional terms and conditions.",
    paragraphs: [
      "10.1 Intellectual rights to the Service, including but not limited to programs, databases, interface, technical developments, logo, trademark, and other means of individualization used on the Service and allowing to implement the Service functionality, belong to CRYPTO ARBY TRADE LIMITED. The Service and its components cannot be copied (reproduced), processed, distributed, published, downloaded, transferred, sold, or otherwise used in whole or in part without the prior written permission of CRYPTO ARBY TRADE LIMITED. Any other use of the Service is strictly prohibited.",
      "10.2 CRYPTO ARBY TRADE LIMITED has no rights to trademarks, service marks, trade names, logos, copyrights, patents, domain names, or other intellectual property belonging to third parties. All intellectual property items mentioned above belong to their respective owners. The rights to third-party content also belong to the respective third parties.",
      "10.3 CRYPTO ARBY TRADE LIMITED has the right to assign or in any other way transfer its rights and obligations arising from its relationship with the User to third parties.",
      "10.4 The Service and the goods provided may be temporarily partially or completely unavailable due to preventive, other work, or for any other technical reasons. The Technical Service has the right to periodically carry out the necessary preventive or other work with or without prior notification of the Users.",
    ],
  },
];
